/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.pojos;



/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record Address(
    Long addressId,
    String city,
    String zip,
    String street
) {

}
