/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.pojos;



/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record PersonAddress(
    Long personId,
    Long addressId
) {

}
