/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.pojos;


import se.soundgood.jooq.enums.Instype;
import se.soundgood.jooq.enums.Skill;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record StudentInstype(
    Long studentId,
    Instype instrumentType,
    Skill skillLevel
) {

}
