/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import se.soundgood.storage.jooq.DefaultSchema;
import se.soundgood.storage.jooq.Keys;
import se.soundgood.storage.jooq.tables.Person.PersonPath;
import se.soundgood.storage.jooq.tables.records.EmailRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Email extends TableImpl<EmailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>email</code>
     */
    public static final Email EMAIL = new Email();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailRecord> getRecordType() {
        return EmailRecord.class;
    }

    /**
     * The column <code>email.person_id</code>.
     */
    public final TableField<EmailRecord, Long> PERSON_ID = createField(DSL.name("person_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>email.email</code>.
     */
    public final TableField<EmailRecord, String> EMAIL_ = createField(DSL.name("email"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private Email(Name alias, Table<EmailRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Email(Name alias, Table<EmailRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>email</code> table reference
     */
    public Email(String alias) {
        this(DSL.name(alias), EMAIL);
    }

    /**
     * Create an aliased <code>email</code> table reference
     */
    public Email(Name alias) {
        this(alias, EMAIL);
    }

    /**
     * Create a <code>email</code> table reference
     */
    public Email() {
        this(DSL.name("email"), null);
    }

    public <O extends Record> Email(Table<O> path, ForeignKey<O, EmailRecord> childPath, InverseForeignKey<O, EmailRecord> parentPath) {
        super(path, childPath, parentPath, EMAIL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmailPath extends Email implements Path<EmailRecord> {
        public <O extends Record> EmailPath(Table<O> path, ForeignKey<O, EmailRecord> childPath, InverseForeignKey<O, EmailRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmailPath(Name alias, Table<EmailRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmailPath as(String alias) {
            return new EmailPath(DSL.name(alias), this);
        }

        @Override
        public EmailPath as(Name alias) {
            return new EmailPath(alias, this);
        }

        @Override
        public EmailPath as(Table<?> alias) {
            return new EmailPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<EmailRecord> getPrimaryKey() {
        return Keys.EMAIL_PKEY;
    }

    @Override
    public List<ForeignKey<EmailRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMAIL__EMAIL_PERSON_ID_FKEY);
    }

    private transient PersonPath _person;

    /**
     * Get the implicit join path to the <code>public.person</code> table.
     */
    public PersonPath person() {
        if (_person == null)
            _person = new PersonPath(this, Keys.EMAIL__EMAIL_PERSON_ID_FKEY, null);

        return _person;
    }

    @Override
    public Email as(String alias) {
        return new Email(DSL.name(alias), this);
    }

    @Override
    public Email as(Name alias) {
        return new Email(alias, this);
    }

    @Override
    public Email as(Table<?> alias) {
        return new Email(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Email rename(String name) {
        return new Email(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Email rename(Name name) {
        return new Email(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Email rename(Table<?> name) {
        return new Email(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email where(Condition condition) {
        return new Email(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Email where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Email where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Email where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Email where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
