/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>student_family_id_seq</code>
     */
    public static final Sequence<Long> STUDENT_FAMILY_ID_SEQ = Internal.createSequence("student_family_id_seq", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
