/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq;


import se.soundgood.jooq.tables.Address;
import se.soundgood.jooq.tables.AvailableInstrument;
import se.soundgood.jooq.tables.ContactPersonStudent;
import se.soundgood.jooq.tables.DbSettings;
import se.soundgood.jooq.tables.Email;
import se.soundgood.jooq.tables.Enrollment;
import se.soundgood.jooq.tables.Instructor;
import se.soundgood.jooq.tables.InstructorInstype;
import se.soundgood.jooq.tables.Instrument;
import se.soundgood.jooq.tables.InstrumentSpecification;
import se.soundgood.jooq.tables.Lease;
import se.soundgood.jooq.tables.Lesson;
import se.soundgood.jooq.tables.Payment;
import se.soundgood.jooq.tables.PaymentDescription;
import se.soundgood.jooq.tables.Person;
import se.soundgood.jooq.tables.PersonAddress;
import se.soundgood.jooq.tables.Phone;
import se.soundgood.jooq.tables.RentPrice;
import se.soundgood.jooq.tables.Student;
import se.soundgood.jooq.tables.StudentHistory;
import se.soundgood.jooq.tables.StudentInstype;
import se.soundgood.jooq.tables.TimeSlot;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>available_instrument</code>.
     */
    public static final AvailableInstrument AVAILABLE_INSTRUMENT = AvailableInstrument.AVAILABLE_INSTRUMENT;

    /**
     * The table <code>contact_person_student</code>.
     */
    public static final ContactPersonStudent CONTACT_PERSON_STUDENT = ContactPersonStudent.CONTACT_PERSON_STUDENT;

    /**
     * The table <code>db_settings</code>.
     */
    public static final DbSettings DB_SETTINGS = DbSettings.DB_SETTINGS;

    /**
     * The table <code>email</code>.
     */
    public static final Email EMAIL = Email.EMAIL;

    /**
     * The table <code>enrollment</code>.
     */
    public static final Enrollment ENROLLMENT = Enrollment.ENROLLMENT;

    /**
     * The table <code>instructor</code>.
     */
    public static final Instructor INSTRUCTOR = Instructor.INSTRUCTOR;

    /**
     * The table <code>instructor_instype</code>.
     */
    public static final InstructorInstype INSTRUCTOR_INSTYPE = InstructorInstype.INSTRUCTOR_INSTYPE;

    /**
     * The table <code>instrument</code>.
     */
    public static final Instrument INSTRUMENT = Instrument.INSTRUMENT;

    /**
     * The table <code>instrument_specification</code>.
     */
    public static final InstrumentSpecification INSTRUMENT_SPECIFICATION = InstrumentSpecification.INSTRUMENT_SPECIFICATION;

    /**
     * The table <code>lease</code>.
     */
    public static final Lease LEASE = Lease.LEASE;

    /**
     * The table <code>lesson</code>.
     */
    public static final Lesson LESSON = Lesson.LESSON;

    /**
     * The table <code>payment</code>.
     */
    public static final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>payment_description</code>.
     */
    public static final PaymentDescription PAYMENT_DESCRIPTION = PaymentDescription.PAYMENT_DESCRIPTION;

    /**
     * The table <code>person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>person_address</code>.
     */
    public static final PersonAddress PERSON_ADDRESS = PersonAddress.PERSON_ADDRESS;

    /**
     * The table <code>phone</code>.
     */
    public static final Phone PHONE = Phone.PHONE;

    /**
     * The table <code>rent_price</code>.
     */
    public static final RentPrice RENT_PRICE = RentPrice.RENT_PRICE;

    /**
     * The table <code>student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>student_history</code>.
     */
    public static final StudentHistory STUDENT_HISTORY = StudentHistory.STUDENT_HISTORY;

    /**
     * The table <code>student_instype</code>.
     */
    public static final StudentInstype STUDENT_INSTYPE = StudentInstype.STUDENT_INSTYPE;

    /**
     * The table <code>time_slot</code>.
     */
    public static final TimeSlot TIME_SLOT = TimeSlot.TIME_SLOT;
}
