/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.jooq.tables.pojos.Address;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>address.address_id</code>.
     */
    public AddressRecord setAddressId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>address.address_id</code>.
     */
    public Long getAddressId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>address.city</code>.
     */
    public AddressRecord setCity(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>address.city</code>.
     */
    public String getCity() {
        return (String) get(1);
    }

    /**
     * Setter for <code>address.zip</code>.
     */
    public AddressRecord setZip(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>address.zip</code>.
     */
    public String getZip() {
        return (String) get(2);
    }

    /**
     * Setter for <code>address.street</code>.
     */
    public AddressRecord setStreet(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>address.street</code>.
     */
    public String getStreet() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(se.soundgood.jooq.tables.Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Long addressId, String city, String zip, String street) {
        super(se.soundgood.jooq.tables.Address.ADDRESS);

        setAddressId(addressId);
        setCity(city);
        setZip(zip);
        setStreet(street);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Address value) {
        super(se.soundgood.jooq.tables.Address.ADDRESS);

        if (value != null) {
            setAddressId(value.addressId());
            setCity(value.city());
            setZip(value.zip());
            setStreet(value.street());
            resetChangedOnNotNull();
        }
    }
}
