/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.jooq.tables.Email;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailRecord extends UpdatableRecordImpl<EmailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>email.person_id</code>.
     */
    public EmailRecord setPersonId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>email.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>email.email</code>.
     */
    public EmailRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>email.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailRecord
     */
    public EmailRecord() {
        super(Email.EMAIL);
    }

    /**
     * Create a detached, initialised EmailRecord
     */
    public EmailRecord(Long personId, String email) {
        super(Email.EMAIL);

        setPersonId(personId);
        setEmail(email);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EmailRecord
     */
    public EmailRecord(se.soundgood.jooq.tables.pojos.Email value) {
        super(Email.EMAIL);

        if (value != null) {
            setPersonId(value.personId());
            setEmail(value.email());
            resetChangedOnNotNull();
        }
    }
}
