/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.jooq.tables.pojos.Instrument;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrumentRecord extends UpdatableRecordImpl<InstrumentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>instrument.instrument_id</code>.
     */
    public InstrumentRecord setInstrumentId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>instrument.instrument_id</code>.
     */
    public Long getInstrumentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>instrument.description</code>.
     */
    public InstrumentRecord setDescription(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>instrument.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>instrument.instrument_specification_id</code>.
     */
    public InstrumentRecord setInstrumentSpecificationId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>instrument.instrument_specification_id</code>.
     */
    public Long getInstrumentSpecificationId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstrumentRecord
     */
    public InstrumentRecord() {
        super(se.soundgood.jooq.tables.Instrument.INSTRUMENT);
    }

    /**
     * Create a detached, initialised InstrumentRecord
     */
    public InstrumentRecord(Long instrumentId, String description, Long instrumentSpecificationId) {
        super(se.soundgood.jooq.tables.Instrument.INSTRUMENT);

        setInstrumentId(instrumentId);
        setDescription(description);
        setInstrumentSpecificationId(instrumentSpecificationId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised InstrumentRecord
     */
    public InstrumentRecord(Instrument value) {
        super(se.soundgood.jooq.tables.Instrument.INSTRUMENT);

        if (value != null) {
            setInstrumentId(value.instrumentId());
            setDescription(value.description());
            setInstrumentSpecificationId(value.instrumentSpecificationId());
            resetChangedOnNotNull();
        }
    }
}
