/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.jooq.tables.pojos.Lease;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaseRecord extends UpdatableRecordImpl<LeaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lease.lease_id</code>.
     */
    public LeaseRecord setLeaseId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>lease.lease_id</code>.
     */
    public Long getLeaseId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lease.rent_date</code>.
     */
    public LeaseRecord setRentDate(LocalDate value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>lease.rent_date</code>.
     */
    public LocalDate getRentDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>lease.return_date</code>.
     */
    public LeaseRecord setReturnDate(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>lease.return_date</code>.
     */
    public LocalDate getReturnDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>lease.instrument_id</code>.
     */
    public LeaseRecord setInstrumentId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>lease.instrument_id</code>.
     */
    public Long getInstrumentId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>lease.student_id</code>.
     */
    public LeaseRecord setStudentId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>lease.student_id</code>.
     */
    public Long getStudentId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>lease.rent_price_id</code>.
     */
    public LeaseRecord setRentPriceId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>lease.rent_price_id</code>.
     */
    public Long getRentPriceId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LeaseRecord
     */
    public LeaseRecord() {
        super(se.soundgood.jooq.tables.Lease.LEASE);
    }

    /**
     * Create a detached, initialised LeaseRecord
     */
    public LeaseRecord(Long leaseId, LocalDate rentDate, LocalDate returnDate, Long instrumentId, Long studentId, Long rentPriceId) {
        super(se.soundgood.jooq.tables.Lease.LEASE);

        setLeaseId(leaseId);
        setRentDate(rentDate);
        setReturnDate(returnDate);
        setInstrumentId(instrumentId);
        setStudentId(studentId);
        setRentPriceId(rentPriceId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LeaseRecord
     */
    public LeaseRecord(Lease value) {
        super(se.soundgood.jooq.tables.Lease.LEASE);

        if (value != null) {
            setLeaseId(value.leaseId());
            setRentDate(value.rentDate());
            setReturnDate(value.returnDate());
            setInstrumentId(value.instrumentId());
            setStudentId(value.studentId());
            setRentPriceId(value.rentPriceId());
            resetChangedOnNotNull();
        }
    }
}
