/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.jooq.tables.PaymentDescription;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentDescriptionRecord extends UpdatableRecordImpl<PaymentDescriptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>payment_description.payment_description_id</code>.
     */
    public PaymentDescriptionRecord setPaymentDescriptionId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>payment_description.payment_description_id</code>.
     */
    public Long getPaymentDescriptionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>payment_description.description</code>.
     */
    public PaymentDescriptionRecord setDescription(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>payment_description.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentDescriptionRecord
     */
    public PaymentDescriptionRecord() {
        super(PaymentDescription.PAYMENT_DESCRIPTION);
    }

    /**
     * Create a detached, initialised PaymentDescriptionRecord
     */
    public PaymentDescriptionRecord(Long paymentDescriptionId, String description) {
        super(PaymentDescription.PAYMENT_DESCRIPTION);

        setPaymentDescriptionId(paymentDescriptionId);
        setDescription(description);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PaymentDescriptionRecord
     */
    public PaymentDescriptionRecord(se.soundgood.jooq.tables.pojos.PaymentDescription value) {
        super(PaymentDescription.PAYMENT_DESCRIPTION);

        if (value != null) {
            setPaymentDescriptionId(value.paymentDescriptionId());
            setDescription(value.description());
            resetChangedOnNotNull();
        }
    }
}
