/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.jooq.tables.pojos.Person;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonRecord extends UpdatableRecordImpl<PersonRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>person.person_id</code>.
     */
    public PersonRecord setPersonId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>person.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>person.first_name</code>.
     */
    public PersonRecord setFirstName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>person.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>person.last_name</code>.
     */
    public PersonRecord setLastName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>person.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>person.ssn</code>.
     */
    public PersonRecord setSsn(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>person.ssn</code>.
     */
    public String getSsn() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonRecord
     */
    public PersonRecord() {
        super(se.soundgood.jooq.tables.Person.PERSON);
    }

    /**
     * Create a detached, initialised PersonRecord
     */
    public PersonRecord(Long personId, String firstName, String lastName, String ssn) {
        super(se.soundgood.jooq.tables.Person.PERSON);

        setPersonId(personId);
        setFirstName(firstName);
        setLastName(lastName);
        setSsn(ssn);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PersonRecord
     */
    public PersonRecord(Person value) {
        super(se.soundgood.jooq.tables.Person.PERSON);

        if (value != null) {
            setPersonId(value.personId());
            setFirstName(value.firstName());
            setLastName(value.lastName());
            setSsn(value.ssn());
            resetChangedOnNotNull();
        }
    }
}
