/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.jooq.tables.PersonAddress;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonAddressRecord extends UpdatableRecordImpl<PersonAddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>person_address.person_id</code>.
     */
    public PersonAddressRecord setPersonId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>person_address.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>person_address.address_id</code>.
     */
    public PersonAddressRecord setAddressId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>person_address.address_id</code>.
     */
    public Long getAddressId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonAddressRecord
     */
    public PersonAddressRecord() {
        super(PersonAddress.PERSON_ADDRESS);
    }

    /**
     * Create a detached, initialised PersonAddressRecord
     */
    public PersonAddressRecord(Long personId, Long addressId) {
        super(PersonAddress.PERSON_ADDRESS);

        setPersonId(personId);
        setAddressId(addressId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PersonAddressRecord
     */
    public PersonAddressRecord(se.soundgood.jooq.tables.pojos.PersonAddress value) {
        super(PersonAddress.PERSON_ADDRESS);

        if (value != null) {
            setPersonId(value.personId());
            setAddressId(value.addressId());
            resetChangedOnNotNull();
        }
    }
}
