/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.jooq.tables.pojos.RentPrice;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentPriceRecord extends UpdatableRecordImpl<RentPriceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rent_price.rent_price_id</code>.
     */
    public RentPriceRecord setRentPriceId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>rent_price.rent_price_id</code>.
     */
    public Long getRentPriceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>rent_price.price</code>.
     */
    public RentPriceRecord setPrice(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>rent_price.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rent_price.from_date</code>.
     */
    public RentPriceRecord setFromDate(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>rent_price.from_date</code>.
     */
    public LocalDate getFromDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>rent_price.to_date</code>.
     */
    public RentPriceRecord setToDate(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>rent_price.to_date</code>.
     */
    public LocalDate getToDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>rent_price.instrument_id</code>.
     */
    public RentPriceRecord setInstrumentId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>rent_price.instrument_id</code>.
     */
    public Long getInstrumentId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RentPriceRecord
     */
    public RentPriceRecord() {
        super(se.soundgood.jooq.tables.RentPrice.RENT_PRICE);
    }

    /**
     * Create a detached, initialised RentPriceRecord
     */
    public RentPriceRecord(Long rentPriceId, Integer price, LocalDate fromDate, LocalDate toDate, Long instrumentId) {
        super(se.soundgood.jooq.tables.RentPrice.RENT_PRICE);

        setRentPriceId(rentPriceId);
        setPrice(price);
        setFromDate(fromDate);
        setToDate(toDate);
        setInstrumentId(instrumentId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RentPriceRecord
     */
    public RentPriceRecord(RentPrice value) {
        super(se.soundgood.jooq.tables.RentPrice.RENT_PRICE);

        if (value != null) {
            setRentPriceId(value.rentPriceId());
            setPrice(value.price());
            setFromDate(value.fromDate());
            setToDate(value.toDate());
            setInstrumentId(value.instrumentId());
            resetChangedOnNotNull();
        }
    }
}
