/*
 * This file is generated by jOOQ.
 */
package se.soundgood.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.YearToSecond;

import se.soundgood.jooq.tables.pojos.TimeSlot;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeSlotRecord extends UpdatableRecordImpl<TimeSlotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>time_slot.time_slot_id</code>.
     */
    public TimeSlotRecord setTimeSlotId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>time_slot.time_slot_id</code>.
     */
    public Long getTimeSlotId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>time_slot.date</code>.
     */
    public TimeSlotRecord setDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>time_slot.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>time_slot.duration</code>.
     */
    public TimeSlotRecord setDuration(YearToSecond value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>time_slot.duration</code>.
     */
    public YearToSecond getDuration() {
        return (YearToSecond) get(2);
    }

    /**
     * Setter for <code>time_slot.location</code>.
     */
    public TimeSlotRecord setLocation(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>time_slot.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>time_slot.lesson_id</code>.
     */
    public TimeSlotRecord setLessonId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>time_slot.lesson_id</code>.
     */
    public Long getLessonId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>time_slot.instructor_id</code>.
     */
    public TimeSlotRecord setInstructorId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>time_slot.instructor_id</code>.
     */
    public Long getInstructorId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>time_slot.payment_id</code>.
     */
    public TimeSlotRecord setPaymentId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>time_slot.payment_id</code>.
     */
    public Long getPaymentId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TimeSlotRecord
     */
    public TimeSlotRecord() {
        super(se.soundgood.jooq.tables.TimeSlot.TIME_SLOT);
    }

    /**
     * Create a detached, initialised TimeSlotRecord
     */
    public TimeSlotRecord(Long timeSlotId, LocalDateTime date, YearToSecond duration, String location, Long lessonId, Long instructorId, Long paymentId) {
        super(se.soundgood.jooq.tables.TimeSlot.TIME_SLOT);

        setTimeSlotId(timeSlotId);
        setDate(date);
        setDuration(duration);
        setLocation(location);
        setLessonId(lessonId);
        setInstructorId(instructorId);
        setPaymentId(paymentId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TimeSlotRecord
     */
    public TimeSlotRecord(TimeSlot value) {
        super(se.soundgood.jooq.tables.TimeSlot.TIME_SLOT);

        if (value != null) {
            setTimeSlotId(value.timeSlotId());
            setDate(value.date());
            setDuration(value.duration());
            setLocation(value.location());
            setLessonId(value.lessonId());
            setInstructorId(value.instructorId());
            setPaymentId(value.paymentId());
            resetChangedOnNotNull();
        }
    }
}
