/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.YearToSecond;

import se.soundgood.storage.jooq.enums.Settings;
import se.soundgood.storage.jooq.tables.DbSettings;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbSettingsRecord extends UpdatableRecordImpl<DbSettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>db_settings.id</code>.
     */
    public DbSettingsRecord setId(Settings value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>db_settings.id</code>.
     */
    public Settings getId() {
        return (Settings) get(0);
    }

    /**
     * Setter for <code>db_settings.max_lease_count</code>.
     */
    public DbSettingsRecord setMaxLeaseCount(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>db_settings.max_lease_count</code>.
     */
    public Integer getMaxLeaseCount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db_settings.max_rent_period</code>.
     */
    public DbSettingsRecord setMaxRentPeriod(YearToSecond value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>db_settings.max_rent_period</code>.
     */
    public YearToSecond getMaxRentPeriod() {
        return (YearToSecond) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Settings> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbSettingsRecord
     */
    public DbSettingsRecord() {
        super(DbSettings.DB_SETTINGS);
    }

    /**
     * Create a detached, initialised DbSettingsRecord
     */
    public DbSettingsRecord(Settings id, Integer maxLeaseCount, YearToSecond maxRentPeriod) {
        super(DbSettings.DB_SETTINGS);

        setId(id);
        setMaxLeaseCount(maxLeaseCount);
        setMaxRentPeriod(maxRentPeriod);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DbSettingsRecord
     */
    public DbSettingsRecord(se.soundgood.storage.jooq.tables.pojos.DbSettings value) {
        super(DbSettings.DB_SETTINGS);

        if (value != null) {
            setId(value.id());
            setMaxLeaseCount(value.maxLeaseCount());
            setMaxRentPeriod(value.maxRentPeriod());
            resetChangedOnNotNull();
        }
    }
}
