/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import se.soundgood.storage.jooq.tables.InstructorReport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstructorReportRecord extends TableRecordImpl<InstructorReportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>instructor_report.Instructor ID</code>.
     */
    public InstructorReportRecord setInstructorId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>instructor_report.Instructor ID</code>.
     */
    public Long getInstructorId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>instructor_report.First Name</code>.
     */
    public InstructorReportRecord setFirstName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>instructor_report.First Name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>instructor_report.Last Name</code>.
     */
    public InstructorReportRecord setLastName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>instructor_report.Last Name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>instructor_report.Lesson Count</code>.
     */
    public InstructorReportRecord setLessonCount(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>instructor_report.Lesson Count</code>.
     */
    public Long getLessonCount() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstructorReportRecord
     */
    public InstructorReportRecord() {
        super(InstructorReport.INSTRUCTOR_REPORT);
    }

    /**
     * Create a detached, initialised InstructorReportRecord
     */
    public InstructorReportRecord(Long instructorId, String firstName, String lastName, Long lessonCount) {
        super(InstructorReport.INSTRUCTOR_REPORT);

        setInstructorId(instructorId);
        setFirstName(firstName);
        setLastName(lastName);
        setLessonCount(lessonCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised InstructorReportRecord
     */
    public InstructorReportRecord(se.soundgood.storage.jooq.tables.pojos.InstructorReport value) {
        super(InstructorReport.INSTRUCTOR_REPORT);

        if (value != null) {
            setInstructorId(value.instructorId());
            setFirstName(value.firstName());
            setLastName(value.lastName());
            setLessonCount(value.lessonCount());
            resetChangedOnNotNull();
        }
    }
}
