/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import se.soundgood.storage.jooq.enums.Instype;
import se.soundgood.storage.jooq.tables.InstrumentSpecification;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrumentSpecificationRecord extends UpdatableRecordImpl<InstrumentSpecificationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>instrument_specification.instrument_specification_id</code>.
     */
    public InstrumentSpecificationRecord setInstrumentSpecificationId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>instrument_specification.instrument_specification_id</code>.
     */
    public Long getInstrumentSpecificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>instrument_specification.type</code>.
     */
    public InstrumentSpecificationRecord setType(Instype value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>instrument_specification.type</code>.
     */
    public Instype getType() {
        return (Instype) get(1);
    }

    /**
     * Setter for <code>instrument_specification.brand</code>.
     */
    public InstrumentSpecificationRecord setBrand(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>instrument_specification.brand</code>.
     */
    public String getBrand() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstrumentSpecificationRecord
     */
    public InstrumentSpecificationRecord() {
        super(InstrumentSpecification.INSTRUMENT_SPECIFICATION);
    }

    /**
     * Create a detached, initialised InstrumentSpecificationRecord
     */
    public InstrumentSpecificationRecord(Long instrumentSpecificationId, Instype type, String brand) {
        super(InstrumentSpecification.INSTRUMENT_SPECIFICATION);

        setInstrumentSpecificationId(instrumentSpecificationId);
        setType(type);
        setBrand(brand);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised InstrumentSpecificationRecord
     */
    public InstrumentSpecificationRecord(se.soundgood.storage.jooq.tables.pojos.InstrumentSpecification value) {
        super(InstrumentSpecification.INSTRUMENT_SPECIFICATION);

        if (value != null) {
            setInstrumentSpecificationId(value.instrumentSpecificationId());
            setType(value.type());
            setBrand(value.brand());
            resetChangedOnNotNull();
        }
    }
}
