/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import se.soundgood.storage.jooq.tables.MonthlyReport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MonthlyReportRecord extends TableRecordImpl<MonthlyReportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>monthly_report.month</code>.
     */
    public MonthlyReportRecord setMonth(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>monthly_report.month</code>.
     */
    public String getMonth() {
        return (String) get(0);
    }

    /**
     * Setter for <code>monthly_report.total</code>.
     */
    public MonthlyReportRecord setTotal(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>monthly_report.total</code>.
     */
    public Long getTotal() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>monthly_report.individual</code>.
     */
    public MonthlyReportRecord setIndividual(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>monthly_report.individual</code>.
     */
    public Long getIndividual() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>monthly_report.Group</code>.
     */
    public MonthlyReportRecord setGroup(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>monthly_report.Group</code>.
     */
    public Long getGroup() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>monthly_report.ensemble</code>.
     */
    public MonthlyReportRecord setEnsemble(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>monthly_report.ensemble</code>.
     */
    public Long getEnsemble() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MonthlyReportRecord
     */
    public MonthlyReportRecord() {
        super(MonthlyReport.MONTHLY_REPORT);
    }

    /**
     * Create a detached, initialised MonthlyReportRecord
     */
    public MonthlyReportRecord(String month, Long total, Long individual, Long group, Long ensemble) {
        super(MonthlyReport.MONTHLY_REPORT);

        setMonth(month);
        setTotal(total);
        setIndividual(individual);
        setGroup(group);
        setEnsemble(ensemble);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MonthlyReportRecord
     */
    public MonthlyReportRecord(se.soundgood.storage.jooq.tables.pojos.MonthlyReport value) {
        super(MonthlyReport.MONTHLY_REPORT);

        if (value != null) {
            setMonth(value.month());
            setTotal(value.total());
            setIndividual(value.individual());
            setGroup(value.group());
            setEnsemble(value.ensemble());
            resetChangedOnNotNull();
        }
    }
}
