/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import se.soundgood.storage.jooq.enums.Mgenre;
import se.soundgood.storage.jooq.tables.NextWeekEnsemble;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NextWeekEnsembleRecord extends TableRecordImpl<NextWeekEnsembleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>next_week_ensemble.Day</code>.
     */
    public NextWeekEnsembleRecord setDay(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>next_week_ensemble.Day</code>.
     */
    public String getDay() {
        return (String) get(0);
    }

    /**
     * Setter for <code>next_week_ensemble.Genre</code>.
     */
    public NextWeekEnsembleRecord setGenre(Mgenre value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>next_week_ensemble.Genre</code>.
     */
    public Mgenre getGenre() {
        return (Mgenre) get(1);
    }

    /**
     * Setter for <code>next_week_ensemble.No of Free Seats</code>.
     */
    public NextWeekEnsembleRecord setNoOfFreeSeats(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>next_week_ensemble.No of Free Seats</code>.
     */
    public String getNoOfFreeSeats() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NextWeekEnsembleRecord
     */
    public NextWeekEnsembleRecord() {
        super(NextWeekEnsemble.NEXT_WEEK_ENSEMBLE);
    }

    /**
     * Create a detached, initialised NextWeekEnsembleRecord
     */
    public NextWeekEnsembleRecord(String day, Mgenre genre, String noOfFreeSeats) {
        super(NextWeekEnsemble.NEXT_WEEK_ENSEMBLE);

        setDay(day);
        setGenre(genre);
        setNoOfFreeSeats(noOfFreeSeats);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NextWeekEnsembleRecord
     */
    public NextWeekEnsembleRecord(se.soundgood.storage.jooq.tables.pojos.NextWeekEnsemble value) {
        super(NextWeekEnsemble.NEXT_WEEK_ENSEMBLE);

        if (value != null) {
            setDay(value.day());
            setGenre(value.genre());
            setNoOfFreeSeats(value.noOfFreeSeats());
            resetChangedOnNotNull();
        }
    }
}
