/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.pojos;



/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record ContactPersonStudent(
    Long studentId,
    Long contactPersonId
) {

}
