/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.pojos;


import se.soundgood.storage.jooq.enums.Instype;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record InstructorInstype(
    Long instructorId,
    Instype instrumentType
) {

}
