/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.pojos;


import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record Lease(
    Long leaseId,
    LocalDate rentDate,
    LocalDate returnDate,
    Long instrumentId,
    Long studentId,
    Long rentPriceId
) {

}
