/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.pojos;


import se.soundgood.storage.jooq.enums.Instype;
import se.soundgood.storage.jooq.enums.Lesstype;
import se.soundgood.storage.jooq.enums.Mgenre;
import se.soundgood.storage.jooq.enums.Skill;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record Lesson(
    Long lessonId,
    Long instructorId,
    Lesstype lessonType,
    Skill skillLevel,
    Integer minStudents,
    Integer maxStudents,
    Instype instrumentType,
    Mgenre musicGenre,
    Long paymentDescriptionId
) {

}
