/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.pojos;



/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record MonthlyReport(
    String month,
    Long total,
    Long individual,
    Long group,
    Long ensemble
) {

}
