/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.pojos;


import se.soundgood.storage.jooq.enums.Mgenre;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record NextWeekEnsemble(
    String day,
    Mgenre genre,
    String noOfFreeSeats
) {

}
