/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.pojos;


import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record RentPrice(
    Long rentPriceId,
    Integer price,
    LocalDate fromDate,
    LocalDate toDate,
    Long instrumentId
) {

}
