/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq.tables.pojos;


import java.time.LocalDateTime;

import org.jooq.types.YearToSecond;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record TimeSlot(
    Long timeSlotId,
    LocalDateTime date,
    YearToSecond duration,
    String location,
    Long lessonId,
    Long instructorId,
    Long paymentId
) {

}
