/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import se.soundgood.storage.jooq.tables.Address;
import se.soundgood.storage.jooq.tables.ContactPersonStudent;
import se.soundgood.storage.jooq.tables.DbSettings;
import se.soundgood.storage.jooq.tables.Email;
import se.soundgood.storage.jooq.tables.Enrollment;
import se.soundgood.storage.jooq.tables.Instructor;
import se.soundgood.storage.jooq.tables.InstructorInstype;
import se.soundgood.storage.jooq.tables.InstructorReport;
import se.soundgood.storage.jooq.tables.Instrument;
import se.soundgood.storage.jooq.tables.InstrumentSpecification;
import se.soundgood.storage.jooq.tables.Lease;
import se.soundgood.storage.jooq.tables.Lesson;
import se.soundgood.storage.jooq.tables.MonthlyReport;
import se.soundgood.storage.jooq.tables.NextWeekEnsemble;
import se.soundgood.storage.jooq.tables.Payment;
import se.soundgood.storage.jooq.tables.PaymentDescription;
import se.soundgood.storage.jooq.tables.Person;
import se.soundgood.storage.jooq.tables.PersonAddress;
import se.soundgood.storage.jooq.tables.Phone;
import se.soundgood.storage.jooq.tables.RentPrice;
import se.soundgood.storage.jooq.tables.Student;
import se.soundgood.storage.jooq.tables.StudentHistory;
import se.soundgood.storage.jooq.tables.StudentInstype;
import se.soundgood.storage.jooq.tables.TimeSlot;
import se.soundgood.storage.jooq.tables.records.InstructorReportRecord;
import se.soundgood.storage.jooq.tables.records.MonthlyReportRecord;
import se.soundgood.storage.jooq.tables.records.NextWeekEnsembleRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>contact_person_student</code>.
     */
    public final ContactPersonStudent CONTACT_PERSON_STUDENT = ContactPersonStudent.CONTACT_PERSON_STUDENT;

    /**
     * The table <code>db_settings</code>.
     */
    public final DbSettings DB_SETTINGS = DbSettings.DB_SETTINGS;

    /**
     * The table <code>email</code>.
     */
    public final Email EMAIL = Email.EMAIL;

    /**
     * The table <code>enrollment</code>.
     */
    public final Enrollment ENROLLMENT = Enrollment.ENROLLMENT;

    /**
     * The table <code>instructor</code>.
     */
    public final Instructor INSTRUCTOR = Instructor.INSTRUCTOR;

    /**
     * The table <code>instructor_instype</code>.
     */
    public final InstructorInstype INSTRUCTOR_INSTYPE = InstructorInstype.INSTRUCTOR_INSTYPE;

    /**
     * The table <code>instructor_report</code>.
     */
    public final InstructorReport INSTRUCTOR_REPORT = InstructorReport.INSTRUCTOR_REPORT;

    /**
     * Call <code>instructor_report</code>.
     */
    public static Result<InstructorReportRecord> INSTRUCTOR_REPORT(
          Configuration configuration
        , Integer _Num
        , LocalDate _StartDate
    ) {
        return configuration.dsl().selectFrom(se.soundgood.storage.jooq.tables.InstructorReport.INSTRUCTOR_REPORT.call(
              _Num
            , _StartDate
        )).fetch();
    }

    /**
     * Get <code>instructor_report</code> as a table.
     */
    public static InstructorReport INSTRUCTOR_REPORT(
          Integer _Num
        , LocalDate _StartDate
    ) {
        return se.soundgood.storage.jooq.tables.InstructorReport.INSTRUCTOR_REPORT.call(
            _Num,
            _StartDate
        );
    }

    /**
     * Get <code>instructor_report</code> as a table.
     */
    public static InstructorReport INSTRUCTOR_REPORT(
          Field<Integer> _Num
        , Field<LocalDate> _StartDate
    ) {
        return se.soundgood.storage.jooq.tables.InstructorReport.INSTRUCTOR_REPORT.call(
            _Num,
            _StartDate
        );
    }

    /**
     * The table <code>instrument</code>.
     */
    public final Instrument INSTRUMENT = Instrument.INSTRUMENT;

    /**
     * The table <code>instrument_specification</code>.
     */
    public final InstrumentSpecification INSTRUMENT_SPECIFICATION = InstrumentSpecification.INSTRUMENT_SPECIFICATION;

    /**
     * The table <code>lease</code>.
     */
    public final Lease LEASE = Lease.LEASE;

    /**
     * The table <code>lesson</code>.
     */
    public final Lesson LESSON = Lesson.LESSON;

    /**
     * The table <code>monthly_report</code>.
     */
    public final MonthlyReport MONTHLY_REPORT = MonthlyReport.MONTHLY_REPORT;

    /**
     * Call <code>monthly_report</code>.
     */
    public static Result<MonthlyReportRecord> MONTHLY_REPORT(
          Configuration configuration
        , String _Year
    ) {
        return configuration.dsl().selectFrom(se.soundgood.storage.jooq.tables.MonthlyReport.MONTHLY_REPORT.call(
              _Year
        )).fetch();
    }

    /**
     * Get <code>monthly_report</code> as a table.
     */
    public static MonthlyReport MONTHLY_REPORT(
          String _Year
    ) {
        return se.soundgood.storage.jooq.tables.MonthlyReport.MONTHLY_REPORT.call(
            _Year
        );
    }

    /**
     * Get <code>monthly_report</code> as a table.
     */
    public static MonthlyReport MONTHLY_REPORT(
          Field<String> _Year
    ) {
        return se.soundgood.storage.jooq.tables.MonthlyReport.MONTHLY_REPORT.call(
            _Year
        );
    }

    /**
     * The table <code>next_week_ensemble</code>.
     */
    public final NextWeekEnsemble NEXT_WEEK_ENSEMBLE = NextWeekEnsemble.NEXT_WEEK_ENSEMBLE;

    /**
     * Call <code>next_week_ensemble</code>.
     */
    public static Result<NextWeekEnsembleRecord> NEXT_WEEK_ENSEMBLE(
          Configuration configuration
        , LocalDate _StartDate
    ) {
        return configuration.dsl().selectFrom(se.soundgood.storage.jooq.tables.NextWeekEnsemble.NEXT_WEEK_ENSEMBLE.call(
              _StartDate
        )).fetch();
    }

    /**
     * Get <code>next_week_ensemble</code> as a table.
     */
    public static NextWeekEnsemble NEXT_WEEK_ENSEMBLE(
          LocalDate _StartDate
    ) {
        return se.soundgood.storage.jooq.tables.NextWeekEnsemble.NEXT_WEEK_ENSEMBLE.call(
            _StartDate
        );
    }

    /**
     * Get <code>next_week_ensemble</code> as a table.
     */
    public static NextWeekEnsemble NEXT_WEEK_ENSEMBLE(
          Field<LocalDate> _StartDate
    ) {
        return se.soundgood.storage.jooq.tables.NextWeekEnsemble.NEXT_WEEK_ENSEMBLE.call(
            _StartDate
        );
    }

    /**
     * The table <code>payment</code>.
     */
    public final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>payment_description</code>.
     */
    public final PaymentDescription PAYMENT_DESCRIPTION = PaymentDescription.PAYMENT_DESCRIPTION;

    /**
     * The table <code>person</code>.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * The table <code>person_address</code>.
     */
    public final PersonAddress PERSON_ADDRESS = PersonAddress.PERSON_ADDRESS;

    /**
     * The table <code>phone</code>.
     */
    public final Phone PHONE = Phone.PHONE;

    /**
     * The table <code>rent_price</code>.
     */
    public final RentPrice RENT_PRICE = RentPrice.RENT_PRICE;

    /**
     * The table <code>student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>student_history</code>.
     */
    public final StudentHistory STUDENT_HISTORY = StudentHistory.STUDENT_HISTORY;

    /**
     * The table <code>student_instype</code>.
     */
    public final StudentInstype STUDENT_INSTYPE = StudentInstype.STUDENT_INSTYPE;

    /**
     * The table <code>time_slot</code>.
     */
    public final TimeSlot TIME_SLOT = TimeSlot.TIME_SLOT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.STUDENT_FAMILY_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Address.ADDRESS,
            ContactPersonStudent.CONTACT_PERSON_STUDENT,
            DbSettings.DB_SETTINGS,
            Email.EMAIL,
            Enrollment.ENROLLMENT,
            Instructor.INSTRUCTOR,
            InstructorInstype.INSTRUCTOR_INSTYPE,
            InstructorReport.INSTRUCTOR_REPORT,
            Instrument.INSTRUMENT,
            InstrumentSpecification.INSTRUMENT_SPECIFICATION,
            Lease.LEASE,
            Lesson.LESSON,
            MonthlyReport.MONTHLY_REPORT,
            NextWeekEnsemble.NEXT_WEEK_ENSEMBLE,
            Payment.PAYMENT,
            PaymentDescription.PAYMENT_DESCRIPTION,
            Person.PERSON,
            PersonAddress.PERSON_ADDRESS,
            Phone.PHONE,
            RentPrice.RENT_PRICE,
            Student.STUDENT,
            StudentHistory.STUDENT_HISTORY,
            StudentInstype.STUDENT_INSTYPE,
            TimeSlot.TIME_SLOT
        );
    }
}
