/*
 * This file is generated by jOOQ.
 */
package se.soundgood.storage.jooq;


import java.time.LocalDate;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;

import se.soundgood.storage.jooq.tables.InstructorReport;
import se.soundgood.storage.jooq.tables.MonthlyReport;
import se.soundgood.storage.jooq.tables.NextWeekEnsemble;
import se.soundgood.storage.jooq.tables.records.InstructorReportRecord;
import se.soundgood.storage.jooq.tables.records.MonthlyReportRecord;
import se.soundgood.storage.jooq.tables.records.NextWeekEnsembleRecord;


/**
 * Convenience access to all stored procedures and functions in the default
 * schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>instructor_report</code>.
     */
    public static Result<InstructorReportRecord> instructorReport(
          Configuration configuration
        , Integer _Num
        , LocalDate _StartDate
    ) {
        return configuration.dsl().selectFrom(se.soundgood.storage.jooq.tables.InstructorReport.INSTRUCTOR_REPORT.call(
              _Num
            , _StartDate
        )).fetch();
    }

    /**
     * Get <code>instructor_report</code> as a table.
     */
    public static InstructorReport instructorReport(
          Integer _Num
        , LocalDate _StartDate
    ) {
        return se.soundgood.storage.jooq.tables.InstructorReport.INSTRUCTOR_REPORT.call(
            _Num,
            _StartDate
        );
    }

    /**
     * Get <code>instructor_report</code> as a table.
     */
    public static InstructorReport instructorReport(
          Field<Integer> _Num
        , Field<LocalDate> _StartDate
    ) {
        return se.soundgood.storage.jooq.tables.InstructorReport.INSTRUCTOR_REPORT.call(
            _Num,
            _StartDate
        );
    }

    /**
     * Call <code>monthly_report</code>.
     */
    public static Result<MonthlyReportRecord> monthlyReport(
          Configuration configuration
        , String _Year
    ) {
        return configuration.dsl().selectFrom(se.soundgood.storage.jooq.tables.MonthlyReport.MONTHLY_REPORT.call(
              _Year
        )).fetch();
    }

    /**
     * Get <code>monthly_report</code> as a table.
     */
    public static MonthlyReport monthlyReport(
          String _Year
    ) {
        return se.soundgood.storage.jooq.tables.MonthlyReport.MONTHLY_REPORT.call(
            _Year
        );
    }

    /**
     * Get <code>monthly_report</code> as a table.
     */
    public static MonthlyReport monthlyReport(
          Field<String> _Year
    ) {
        return se.soundgood.storage.jooq.tables.MonthlyReport.MONTHLY_REPORT.call(
            _Year
        );
    }

    /**
     * Call <code>next_week_ensemble</code>.
     */
    public static Result<NextWeekEnsembleRecord> nextWeekEnsemble(
          Configuration configuration
        , LocalDate _StartDate
    ) {
        return configuration.dsl().selectFrom(se.soundgood.storage.jooq.tables.NextWeekEnsemble.NEXT_WEEK_ENSEMBLE.call(
              _StartDate
        )).fetch();
    }

    /**
     * Get <code>next_week_ensemble</code> as a table.
     */
    public static NextWeekEnsemble nextWeekEnsemble(
          LocalDate _StartDate
    ) {
        return se.soundgood.storage.jooq.tables.NextWeekEnsemble.NEXT_WEEK_ENSEMBLE.call(
            _StartDate
        );
    }

    /**
     * Get <code>next_week_ensemble</code> as a table.
     */
    public static NextWeekEnsemble nextWeekEnsemble(
          Field<LocalDate> _StartDate
    ) {
        return se.soundgood.storage.jooq.tables.NextWeekEnsemble.NEXT_WEEK_ENSEMBLE.call(
            _StartDate
        );
    }
}
